export default [
    {
        id: 1,
        brand: "Audi A1 S-Line",
        cost: 45,
        model: "Audi",
        mark: "A1",
        year: 2012,
        doors: "4/5",
        ac: "Yes",
        transmission: "Manual",
        fuel: "Gasoline",
        link: "https://imgbox.io/ib/oZmRQPDacr.jpg"
    },
    {
        id: 2,
        brand: "VW Golf 6",
        cost: 37,
        model: "Golf 6",
        mark: "Volkswagen",
        year: 2008,
        doors: "4/5",
        ac: "Yes",
        transmission: "Manual",
        fuel: "Diesel",
        link: "https://imgbox.io/ib/nKLdWeXXmK.jpg"
    },
    {
        id: 3,
        brand: "Toyota Camry",
        cost: 30,
        model: "Camry",
        mark: "Toyota",
        year: 2006,
        doors: "4/5",
        ac: "Yes",
        transmission: "Automatic",
        fuel: "Hybrid",
        link: "https://imgbox.io/ib/wf8FZgu1oJ.jpg"
    },
    {
        id: 4,
        brand: "BMW 320 ModernLine",
        cost: 35,
        model: 320,
        mark: "BMW",
        year: 2012,
        doors: "4/5",
        ac: "Yes",
        transmission: "Manual",
        fuel: "Diesel",
        link: "https://imgbox.io/ib/NeDogJzr7s.jpg"
    },
    {
        id: 5,
        brand: "Mercedes Benz GLK",
        cost: 50,
        model: "Benz GLK",
        mark: "Mercedes",
        year: 2006,
        doors: "4/5",
        ac: "Yes",
        transmission: "Manual",
        fuel: "Diesel",
        link: "https://imgbox.io/ib/uhdhuQjVSX.jpg"
    },
    {
        id: 6,
        brand: "VW Passat CC",
        cost: 25,
        model: "Passat CC",
        mark: "Volkswagen",
        year: 2008,
        doors: "4/5",
        ac: "Yes",
        transmission: "Automatic",
        fuel: "Gasoline",
        link: "https://imgbox.io/ib/m0tZs34NYZ.jpg"
    }
]